[2023-08-24T18:18:41.551+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: nikeProducts_dag.step_2_task manual__2023-08-24T18:18:37.739147+00:00 [queued]>
[2023-08-24T18:18:41.559+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: nikeProducts_dag.step_2_task manual__2023-08-24T18:18:37.739147+00:00 [queued]>
[2023-08-24T18:18:41.560+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-08-24T18:18:41.561+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 2
[2023-08-24T18:18:41.561+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-08-24T18:18:41.572+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): step_2_task> on 2023-08-24 18:18:37.739147+00:00
[2023-08-24T18:18:41.580+0000] {standard_task_runner.py:55} INFO - Started process 43471 to run task
[2023-08-24T18:18:41.584+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'nikeProducts_dag', 'step_2_task', 'manual__2023-08-24T18:18:37.739147+00:00', '--job-id', '95', '--raw', '--subdir', 'DAGS_FOLDER/nikeProducts_dag.py', '--cfg-path', '/tmp/tmpiu87sjrb']
[2023-08-24T18:18:41.587+0000] {standard_task_runner.py:83} INFO - Job 95: Subtask step_2_task
[2023-08-24T18:18:41.677+0000] {task_command.py:376} INFO - Running <TaskInstance: nikeProducts_dag.step_2_task manual__2023-08-24T18:18:37.739147+00:00 [running]> on host 5879ed69cda2
[2023-08-24T18:18:41.759+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=nikeProducts_dag
AIRFLOW_CTX_TASK_ID=step_2_task
AIRFLOW_CTX_EXECUTION_DATE=2023-08-24T18:18:37.739147+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-08-24T18:18:37.739147+00:00
[2023-08-24T18:18:41.775+0000] {logging_mixin.py:120} INFO - products_etl.csv
[2023-08-24T18:18:41.981+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/scripts/transform_data.py", line 25, in main
    transformed_df: pd.DataFrame = df[['id', 'UID', 'cloudProdID', 'productID', 'shortID', 'colorNum', 'title', 'subtitle', 'category', 'type', 'currency', 'fullPrice', 'currentPrice', 'TopColor', 'channel', 'short_description', 'label', 'prebuildId', 'prod_url', 'color-ID', 'color-Description', 'color-Label', 'color-Image-url', 'color-FullPrice', 'color-CurrentPrice', 'rating', 'sale', 'customizable', 'ExtendedSizing', 'inStock', 'ComingSoon', 'BestSeller', 'Excluded', 'GiftCard', 'Jersey', 'Launch', 'MemberExclusive', 'NBA', 'NFL', 'Sustainable', 'color-Discount', 'color-BestSeller', 'color-InStock', 'color-MemberExclusive', 'color-New']]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/frame.py", line 3464, in __getitem__
    indexer = self.loc._get_listlike_indexer(key, axis=1)[1]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/indexing.py", line 1314, in _get_listlike_indexer
    self._validate_read_indexer(keyarr, indexer, axis)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/indexing.py", line 1377, in _validate_read_indexer
    raise KeyError(f"{not_found} not in index")
KeyError: "['id'] not in index"
[2023-08-24T18:18:41.998+0000] {taskinstance.py:1406} INFO - Marking task as UP_FOR_RETRY. dag_id=nikeProducts_dag, task_id=step_2_task, execution_date=20230824T181837, start_date=20230824T181841, end_date=20230824T181841
[2023-08-24T18:18:42.009+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 95 for task step_2_task ("['id'] not in index"; 43471)
[2023-08-24T18:18:42.040+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2023-08-24T18:18:42.068+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
