[2023-08-24T16:41:56.718+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: nikeProducts_dag.step_1_task manual__2023-08-24T16:41:55.618700+00:00 [queued]>
[2023-08-24T16:41:56.727+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: nikeProducts_dag.step_1_task manual__2023-08-24T16:41:55.618700+00:00 [queued]>
[2023-08-24T16:41:56.728+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-08-24T16:41:56.729+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 2
[2023-08-24T16:41:56.729+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-08-24T16:41:56.741+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): step_1_task> on 2023-08-24 16:41:55.618700+00:00
[2023-08-24T16:41:56.752+0000] {standard_task_runner.py:55} INFO - Started process 38597 to run task
[2023-08-24T16:41:56.756+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'nikeProducts_dag', 'step_1_task', 'manual__2023-08-24T16:41:55.618700+00:00', '--job-id', '53', '--raw', '--subdir', 'DAGS_FOLDER/nikeProducts_dag.py', '--cfg-path', '/tmp/tmp734nm4yn']
[2023-08-24T16:41:56.758+0000] {standard_task_runner.py:83} INFO - Job 53: Subtask step_1_task
[2023-08-24T16:41:56.815+0000] {task_command.py:376} INFO - Running <TaskInstance: nikeProducts_dag.step_1_task manual__2023-08-24T16:41:55.618700+00:00 [running]> on host 5879ed69cda2
[2023-08-24T16:41:56.869+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=nikeProducts_dag
AIRFLOW_CTX_TASK_ID=step_1_task
AIRFLOW_CTX_EXECUTION_DATE=2023-08-24T16:41:55.618700+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-08-24T16:41:55.618700+00:00
[2023-08-24T16:41:56.871+0000] {logging_mixin.py:120} INFO - products.csv mapped to products_etl.csv
[2023-08-24T16:41:56.949+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/scripts/get_data.py", line 18, in main
    df.to_csv(raw_destination)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 3482, in to_csv
    storage_options=storage_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/formats/format.py", line 1105, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/formats/csvs.py", line 243, in save
    storage_options=self.storage_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dags/files/output/products_etl.csv'
[2023-08-24T16:41:56.964+0000] {taskinstance.py:1406} INFO - Marking task as UP_FOR_RETRY. dag_id=nikeProducts_dag, task_id=step_1_task, execution_date=20230824T164155, start_date=20230824T164156, end_date=20230824T164156
[2023-08-24T16:41:56.973+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 53 for task step_1_task ([Errno 2] No such file or directory: '/opt/airflow/dags/files/output/products_etl.csv'; 38597)
[2023-08-24T16:41:57.017+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2023-08-24T16:41:57.046+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
