[2023-08-24T16:51:07.050+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: nikeProducts_dag.step_2_task manual__2023-08-24T16:51:04.087661+00:00 [queued]>
[2023-08-24T16:51:07.056+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: nikeProducts_dag.step_2_task manual__2023-08-24T16:51:04.087661+00:00 [queued]>
[2023-08-24T16:51:07.057+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-08-24T16:51:07.057+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 2
[2023-08-24T16:51:07.058+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-08-24T16:51:07.065+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): step_2_task> on 2023-08-24 16:51:04.087661+00:00
[2023-08-24T16:51:07.070+0000] {standard_task_runner.py:55} INFO - Started process 39071 to run task
[2023-08-24T16:51:07.073+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'nikeProducts_dag', 'step_2_task', 'manual__2023-08-24T16:51:04.087661+00:00', '--job-id', '60', '--raw', '--subdir', 'DAGS_FOLDER/nikeProducts_dag.py', '--cfg-path', '/tmp/tmp1rkru8bc']
[2023-08-24T16:51:07.075+0000] {standard_task_runner.py:83} INFO - Job 60: Subtask step_2_task
[2023-08-24T16:51:07.128+0000] {task_command.py:376} INFO - Running <TaskInstance: nikeProducts_dag.step_2_task manual__2023-08-24T16:51:04.087661+00:00 [running]> on host 5879ed69cda2
[2023-08-24T16:51:07.176+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=nikeProducts_dag
AIRFLOW_CTX_TASK_ID=step_2_task
AIRFLOW_CTX_EXECUTION_DATE=2023-08-24T16:51:04.087661+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-08-24T16:51:04.087661+00:00
[2023-08-24T16:51:07.186+0000] {logging_mixin.py:120} INFO - products_etl.csv
[2023-08-24T16:51:07.259+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/scripts/transform_data.py", line 15, in main
    kwargs['ti'].xcom_push(key='data', value=df)
KeyError: 'ti'
[2023-08-24T16:51:07.268+0000] {taskinstance.py:1406} INFO - Marking task as UP_FOR_RETRY. dag_id=nikeProducts_dag, task_id=step_2_task, execution_date=20230824T165104, start_date=20230824T165107, end_date=20230824T165107
[2023-08-24T16:51:07.275+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 60 for task step_2_task ('ti'; 39071)
[2023-08-24T16:51:07.287+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2023-08-24T16:51:07.306+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
