[2023-08-24T16:59:42.167+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: nikeProducts_dag.step_2_task manual__2023-08-24T16:54:37.761325+00:00 [queued]>
[2023-08-24T16:59:42.174+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: nikeProducts_dag.step_2_task manual__2023-08-24T16:54:37.761325+00:00 [queued]>
[2023-08-24T16:59:42.175+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-08-24T16:59:42.175+0000] {taskinstance.py:1363} INFO - Starting attempt 2 of 2
[2023-08-24T16:59:42.176+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-08-24T16:59:42.183+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): step_2_task> on 2023-08-24 16:54:37.761325+00:00
[2023-08-24T16:59:42.188+0000] {standard_task_runner.py:55} INFO - Started process 39519 to run task
[2023-08-24T16:59:42.193+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'nikeProducts_dag', 'step_2_task', 'manual__2023-08-24T16:54:37.761325+00:00', '--job-id', '69', '--raw', '--subdir', 'DAGS_FOLDER/nikeProducts_dag.py', '--cfg-path', '/tmp/tmp0wiwl5pw']
[2023-08-24T16:59:42.195+0000] {standard_task_runner.py:83} INFO - Job 69: Subtask step_2_task
[2023-08-24T16:59:42.247+0000] {task_command.py:376} INFO - Running <TaskInstance: nikeProducts_dag.step_2_task manual__2023-08-24T16:54:37.761325+00:00 [running]> on host 5879ed69cda2
[2023-08-24T16:59:42.294+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=nikeProducts_dag
AIRFLOW_CTX_TASK_ID=step_2_task
AIRFLOW_CTX_EXECUTION_DATE=2023-08-24T16:54:37.761325+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-08-24T16:54:37.761325+00:00
[2023-08-24T16:59:42.303+0000] {logging_mixin.py:120} INFO - products_etl.csv
[2023-08-24T16:59:42.356+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/scripts/transform_data.py", line 15, in main
    kwargs['ti'].xcom_push(key='data', value=df)
KeyError: 'ti'
[2023-08-24T16:59:42.366+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=nikeProducts_dag, task_id=step_2_task, execution_date=20230824T165437, start_date=20230824T165942, end_date=20230824T165942
[2023-08-24T16:59:42.378+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 69 for task step_2_task ('ti'; 39519)
[2023-08-24T16:59:42.407+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2023-08-24T16:59:42.430+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
