[2023-08-27T08:15:53.066+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: nikeProducts_dag.transform_task manual__2023-08-27T08:15:49.848708+00:00 [queued]>
[2023-08-27T08:15:53.073+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: nikeProducts_dag.transform_task manual__2023-08-27T08:15:49.848708+00:00 [queued]>
[2023-08-27T08:15:53.073+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-08-27T08:15:53.074+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 2
[2023-08-27T08:15:53.074+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-08-27T08:15:53.082+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): transform_task> on 2023-08-27 08:15:49.848708+00:00
[2023-08-27T08:15:53.087+0000] {standard_task_runner.py:55} INFO - Started process 294 to run task
[2023-08-27T08:15:53.092+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'nikeProducts_dag', 'transform_task', 'manual__2023-08-27T08:15:49.848708+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/nikeProducts_dag.py', '--cfg-path', '/tmp/tmpomk3tf7t']
[2023-08-27T08:15:53.094+0000] {standard_task_runner.py:83} INFO - Job 12: Subtask transform_task
[2023-08-27T08:15:53.155+0000] {task_command.py:376} INFO - Running <TaskInstance: nikeProducts_dag.transform_task manual__2023-08-27T08:15:49.848708+00:00 [running]> on host 879040e27dc6
[2023-08-27T08:15:53.209+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=nikeProducts_dag
AIRFLOW_CTX_TASK_ID=transform_task
AIRFLOW_CTX_EXECUTION_DATE=2023-08-27T08:15:49.848708+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-08-27T08:15:49.848708+00:00
[2023-08-27T08:15:53.218+0000] {logging_mixin.py:120} INFO - products_etl.csv
[2023-08-27T08:15:53.312+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/arrays/integer.py", line 126, in safe_cast
    return values.astype(dtype, casting="safe", copy=copy)
TypeError: Cannot cast array data from dtype('float64') to dtype('int64') according to the rule 'safe'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/products_scripts/transform_data.py", line 19, in main
    df['rating'] = df['rating'].astype('Int64')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 5815, in astype
    new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/internals/managers.py", line 418, in astype
    return self.apply("astype", dtype=dtype, copy=copy, errors=errors)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/internals/managers.py", line 327, in apply
    applied = getattr(b, f)(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/internals/blocks.py", line 591, in astype
    new_values = astype_array_safe(values, dtype, copy=copy, errors=errors)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/dtypes/cast.py", line 1309, in astype_array_safe
    new_values = astype_array(values, dtype, copy=copy)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/dtypes/cast.py", line 1257, in astype_array
    values = astype_nansafe(values, dtype, copy=copy)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/dtypes/cast.py", line 1105, in astype_nansafe
    return dtype.construct_array_type()._from_sequence(arr, dtype=dtype, copy=copy)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/arrays/integer.py", line 323, in _from_sequence
    values, mask = coerce_to_array(scalars, dtype=dtype, copy=copy)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/arrays/integer.py", line 229, in coerce_to_array
    values = safe_cast(values, dtype, copy=False)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/arrays/integer.py", line 135, in safe_cast
    ) from err
TypeError: cannot safely cast non-equivalent float64 to int64
[2023-08-27T08:15:53.327+0000] {taskinstance.py:1406} INFO - Marking task as UP_FOR_RETRY. dag_id=nikeProducts_dag, task_id=transform_task, execution_date=20230827T081549, start_date=20230827T081553, end_date=20230827T081553
[2023-08-27T08:15:53.335+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 12 for task transform_task (cannot safely cast non-equivalent float64 to int64; 294)
[2023-08-27T08:15:53.384+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2023-08-27T08:15:53.407+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
