[2023-08-28T17:59:52.605+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: nikeDates_dag.transform_task scheduled__2022-03-01T00:00:00+00:00 [queued]>
[2023-08-28T17:59:52.617+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: nikeDates_dag.transform_task scheduled__2022-03-01T00:00:00+00:00 [queued]>
[2023-08-28T17:59:52.618+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-08-28T17:59:52.618+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 2
[2023-08-28T17:59:52.619+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-08-28T17:59:52.635+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): transform_task> on 2022-03-01 00:00:00+00:00
[2023-08-28T17:59:52.649+0000] {standard_task_runner.py:55} INFO - Started process 188 to run task
[2023-08-28T17:59:52.655+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'nikeDates_dag', 'transform_task', 'scheduled__2022-03-01T00:00:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/nikeDates_dag.py', '--cfg-path', '/tmp/tmp_1j53xr8']
[2023-08-28T17:59:52.657+0000] {standard_task_runner.py:83} INFO - Job 11: Subtask transform_task
[2023-08-28T17:59:52.762+0000] {task_command.py:376} INFO - Running <TaskInstance: nikeDates_dag.transform_task scheduled__2022-03-01T00:00:00+00:00 [running]> on host 7eee6ddbeacd
[2023-08-28T17:59:52.880+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=nikeDates_dag
AIRFLOW_CTX_TASK_ID=transform_task
AIRFLOW_CTX_EXECUTION_DATE=2022-03-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-03-01T00:00:00+00:00
[2023-08-28T17:59:52.908+0000] {logging_mixin.py:120} INFO - sales_etl.csv
[2023-08-28T17:59:52.973+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dates_scripts/transform_data.py", line 20, in main
    transformed_df: pd.DataFrame = df[["ticket_id", "UID", "currency", "sales", "quantity", "date", "year", "month", "day"]]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/frame.py", line 3464, in __getitem__
    indexer = self.loc._get_listlike_indexer(key, axis=1)[1]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/indexing.py", line 1314, in _get_listlike_indexer
    self._validate_read_indexer(keyarr, indexer, axis)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/indexing.py", line 1377, in _validate_read_indexer
    raise KeyError(f"{not_found} not in index")
KeyError: "['ticket_id'] not in index"
[2023-08-28T17:59:52.989+0000] {taskinstance.py:1406} INFO - Marking task as UP_FOR_RETRY. dag_id=nikeDates_dag, task_id=transform_task, execution_date=20220301T000000, start_date=20230828T175952, end_date=20230828T175952
[2023-08-28T17:59:53.020+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 11 for task transform_task ("['ticket_id'] not in index"; 188)
[2023-08-28T17:59:53.065+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2023-08-28T17:59:53.105+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
