[2023-08-27T08:12:04.104+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: nikeProducts_dag.transform_task manual__2023-08-27T08:12:01.293512+00:00 [queued]>
[2023-08-27T08:12:04.111+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: nikeProducts_dag.transform_task manual__2023-08-27T08:12:01.293512+00:00 [queued]>
[2023-08-27T08:12:04.112+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-08-27T08:12:04.112+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 2
[2023-08-27T08:12:04.113+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-08-27T08:12:04.120+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): transform_task> on 2023-08-27 08:12:01.293512+00:00
[2023-08-27T08:12:04.125+0000] {standard_task_runner.py:55} INFO - Started process 93 to run task
[2023-08-27T08:12:04.129+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'nikeProducts_dag', 'transform_task', 'manual__2023-08-27T08:12:01.293512+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/nikeProducts_dag.py', '--cfg-path', '/tmp/tmpycxhwhpk']
[2023-08-27T08:12:04.132+0000] {standard_task_runner.py:83} INFO - Job 8: Subtask transform_task
[2023-08-27T08:12:04.186+0000] {task_command.py:376} INFO - Running <TaskInstance: nikeProducts_dag.transform_task manual__2023-08-27T08:12:01.293512+00:00 [running]> on host 879040e27dc6
[2023-08-27T08:12:04.231+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=nikeProducts_dag
AIRFLOW_CTX_TASK_ID=transform_task
AIRFLOW_CTX_EXECUTION_DATE=2023-08-27T08:12:01.293512+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-08-27T08:12:01.293512+00:00
[2023-08-27T08:12:04.244+0000] {logging_mixin.py:120} INFO - products_etl.csv
[2023-08-27T08:12:04.341+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/products_scripts/transform_data.py", line 15, in main
    df['rating'].fillna(None, inplace=True)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/series.py", line 4822, in fillna
    downcast=downcast,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 6313, in fillna
    value, method = validate_fillna_kwargs(value, method)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_validators.py", line 370, in validate_fillna_kwargs
    raise ValueError("Must specify a fill 'value' or 'method'.")
ValueError: Must specify a fill 'value' or 'method'.
[2023-08-27T08:12:04.352+0000] {taskinstance.py:1406} INFO - Marking task as UP_FOR_RETRY. dag_id=nikeProducts_dag, task_id=transform_task, execution_date=20230827T081201, start_date=20230827T081204, end_date=20230827T081204
[2023-08-27T08:12:04.361+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 8 for task transform_task (Must specify a fill 'value' or 'method'.; 93)
[2023-08-27T08:12:04.381+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2023-08-27T08:12:04.402+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
